/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ActivateDTOInner = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ActivateDTOInner model module.
   * @module model/ActivateDTOInner
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ActivateDTOInner</code>.
   * @alias module:model/ActivateDTOInner
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ActivateDTOInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActivateDTOInner} obj Optional instance to populate.
   * @return {module:model/ActivateDTOInner} The populated <code>ActivateDTOInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('activateLowerImageVersion')) {
        obj['activateLowerImageVersion'] = ApiClient.convertToType(data['activateLowerImageVersion'], 'Boolean');
      }
      if (data.hasOwnProperty('deviceUpgradeMode')) {
        obj['deviceUpgradeMode'] = ApiClient.convertToType(data['deviceUpgradeMode'], 'String');
      }
      if (data.hasOwnProperty('deviceUuid')) {
        obj['deviceUuid'] = ApiClient.convertToType(data['deviceUuid'], 'String');
      }
      if (data.hasOwnProperty('distributeIfNeeded')) {
        obj['distributeIfNeeded'] = ApiClient.convertToType(data['distributeIfNeeded'], 'Boolean');
      }
      if (data.hasOwnProperty('imageUuidList')) {
        obj['imageUuidList'] = ApiClient.convertToType(data['imageUuidList'], ['String']);
      }
      if (data.hasOwnProperty('smuImageUuidList')) {
        obj['smuImageUuidList'] = ApiClient.convertToType(data['smuImageUuidList'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} activateLowerImageVersion
   */
  exports.prototype['activateLowerImageVersion'] = undefined;
  /**
   * @member {String} deviceUpgradeMode
   */
  exports.prototype['deviceUpgradeMode'] = undefined;
  /**
   * @member {String} deviceUuid
   */
  exports.prototype['deviceUuid'] = undefined;
  /**
   * @member {Boolean} distributeIfNeeded
   */
  exports.prototype['distributeIfNeeded'] = undefined;
  /**
   * @member {Array.<String>} imageUuidList
   */
  exports.prototype['imageUuidList'] = undefined;
  /**
   * @member {Array.<String>} smuImageUuidList
   */
  exports.prototype['smuImageUuidList'] = undefined;



  return exports;
}));


