/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ClientDetailResponseResponseConnectionInfo = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ClientDetailResponseResponseConnectionInfo model module.
   * @module model/ClientDetailResponseResponseConnectionInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ClientDetailResponseResponseConnectionInfo</code>.
   * @alias module:model/ClientDetailResponseResponseConnectionInfo
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>ClientDetailResponseResponseConnectionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientDetailResponseResponseConnectionInfo} obj Optional instance to populate.
   * @return {module:model/ClientDetailResponseResponseConnectionInfo} The populated <code>ClientDetailResponseResponseConnectionInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('hostType')) {
        obj['hostType'] = ApiClient.convertToType(data['hostType'], 'String');
      }
      if (data.hasOwnProperty('nwDeviceName')) {
        obj['nwDeviceName'] = ApiClient.convertToType(data['nwDeviceName'], 'String');
      }
      if (data.hasOwnProperty('nwDeviceMac')) {
        obj['nwDeviceMac'] = ApiClient.convertToType(data['nwDeviceMac'], 'String');
      }
      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
      if (data.hasOwnProperty('band')) {
        obj['band'] = ApiClient.convertToType(data['band'], 'String');
      }
      if (data.hasOwnProperty('spatialStream')) {
        obj['spatialStream'] = ApiClient.convertToType(data['spatialStream'], 'String');
      }
      if (data.hasOwnProperty('channel')) {
        obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
      }
      if (data.hasOwnProperty('channelWidth')) {
        obj['channelWidth'] = ApiClient.convertToType(data['channelWidth'], 'String');
      }
      if (data.hasOwnProperty('wmm')) {
        obj['wmm'] = ApiClient.convertToType(data['wmm'], 'String');
      }
      if (data.hasOwnProperty('uapsd')) {
        obj['uapsd'] = ApiClient.convertToType(data['uapsd'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} hostType
   */
  exports.prototype['hostType'] = undefined;
  /**
   * @member {String} nwDeviceName
   */
  exports.prototype['nwDeviceName'] = undefined;
  /**
   * @member {String} nwDeviceMac
   */
  exports.prototype['nwDeviceMac'] = undefined;
  /**
   * @member {String} protocol
   */
  exports.prototype['protocol'] = undefined;
  /**
   * @member {String} band
   */
  exports.prototype['band'] = undefined;
  /**
   * @member {String} spatialStream
   */
  exports.prototype['spatialStream'] = undefined;
  /**
   * @member {String} channel
   */
  exports.prototype['channel'] = undefined;
  /**
   * @member {String} channelWidth
   */
  exports.prototype['channelWidth'] = undefined;
  /**
   * @member {String} wmm
   */
  exports.prototype['wmm'] = undefined;
  /**
   * @member {String} uapsd
   */
  exports.prototype['uapsd'] = undefined;
  /**
   * @member {String} timestamp
   */
  exports.prototype['timestamp'] = undefined;



  return exports;
}));


