/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ClientDetailResponseResponseDetailHealthScore', 'model/ClientDetailResponseResponseDetailOnboarding'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ClientDetailResponseResponseDetailHealthScore'), require('./ClientDetailResponseResponseDetailOnboarding'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ClientDetailResponseResponseDetail = factory(root.Swagger.ApiClient, root.Swagger.ClientDetailResponseResponseDetailHealthScore, root.Swagger.ClientDetailResponseResponseDetailOnboarding);
  }
}(this, function(ApiClient, ClientDetailResponseResponseDetailHealthScore, ClientDetailResponseResponseDetailOnboarding) {
  'use strict';




  /**
   * The ClientDetailResponseResponseDetail model module.
   * @module model/ClientDetailResponseResponseDetail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ClientDetailResponseResponseDetail</code>.
   * @alias module:model/ClientDetailResponseResponseDetail
   * @class
   */
  var exports = function() {
    var _this = this;




































  };

  /**
   * Constructs a <code>ClientDetailResponseResponseDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientDetailResponseResponseDetail} obj Optional instance to populate.
   * @return {module:model/ClientDetailResponseResponseDetail} The populated <code>ClientDetailResponseResponseDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('connectionStatus')) {
        obj['connectionStatus'] = ApiClient.convertToType(data['connectionStatus'], 'String');
      }
      if (data.hasOwnProperty('hostType')) {
        obj['hostType'] = ApiClient.convertToType(data['hostType'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('hostName')) {
        obj['hostName'] = ApiClient.convertToType(data['hostName'], 'String');
      }
      if (data.hasOwnProperty('hostOs')) {
        obj['hostOs'] = ApiClient.convertToType(data['hostOs'], 'String');
      }
      if (data.hasOwnProperty('hostVersion')) {
        obj['hostVersion'] = ApiClient.convertToType(data['hostVersion'], 'String');
      }
      if (data.hasOwnProperty('subType')) {
        obj['subType'] = ApiClient.convertToType(data['subType'], 'String');
      }
      if (data.hasOwnProperty('lastUpdated')) {
        obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'String');
      }
      if (data.hasOwnProperty('healthScore')) {
        obj['healthScore'] = ApiClient.convertToType(data['healthScore'], [ClientDetailResponseResponseDetailHealthScore]);
      }
      if (data.hasOwnProperty('hostMac')) {
        obj['hostMac'] = ApiClient.convertToType(data['hostMac'], 'String');
      }
      if (data.hasOwnProperty('hostIpV4')) {
        obj['hostIpV4'] = ApiClient.convertToType(data['hostIpV4'], 'String');
      }
      if (data.hasOwnProperty('hostIpV6')) {
        obj['hostIpV6'] = ApiClient.convertToType(data['hostIpV6'], ['String']);
      }
      if (data.hasOwnProperty('authType')) {
        obj['authType'] = ApiClient.convertToType(data['authType'], 'String');
      }
      if (data.hasOwnProperty('vlanId')) {
        obj['vlanId'] = ApiClient.convertToType(data['vlanId'], 'String');
      }
      if (data.hasOwnProperty('ssid')) {
        obj['ssid'] = ApiClient.convertToType(data['ssid'], 'String');
      }
      if (data.hasOwnProperty('frequency')) {
        obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
      }
      if (data.hasOwnProperty('channel')) {
        obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
      }
      if (data.hasOwnProperty('apGroup')) {
        obj['apGroup'] = ApiClient.convertToType(data['apGroup'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('clientConnection')) {
        obj['clientConnection'] = ApiClient.convertToType(data['clientConnection'], 'String');
      }
      if (data.hasOwnProperty('connectedDevice')) {
        obj['connectedDevice'] = ApiClient.convertToType(data['connectedDevice'], ['String']);
      }
      if (data.hasOwnProperty('issueCount')) {
        obj['issueCount'] = ApiClient.convertToType(data['issueCount'], 'String');
      }
      if (data.hasOwnProperty('rssi')) {
        obj['rssi'] = ApiClient.convertToType(data['rssi'], 'String');
      }
      if (data.hasOwnProperty('avgRssi')) {
        obj['avgRssi'] = ApiClient.convertToType(data['avgRssi'], 'String');
      }
      if (data.hasOwnProperty('snr')) {
        obj['snr'] = ApiClient.convertToType(data['snr'], 'String');
      }
      if (data.hasOwnProperty('avgSnr')) {
        obj['avgSnr'] = ApiClient.convertToType(data['avgSnr'], 'String');
      }
      if (data.hasOwnProperty('dataRate')) {
        obj['dataRate'] = ApiClient.convertToType(data['dataRate'], 'String');
      }
      if (data.hasOwnProperty('txBytes')) {
        obj['txBytes'] = ApiClient.convertToType(data['txBytes'], 'String');
      }
      if (data.hasOwnProperty('rxBytes')) {
        obj['rxBytes'] = ApiClient.convertToType(data['rxBytes'], 'String');
      }
      if (data.hasOwnProperty('dnsSuccess')) {
        obj['dnsSuccess'] = ApiClient.convertToType(data['dnsSuccess'], 'String');
      }
      if (data.hasOwnProperty('dnsFailure')) {
        obj['dnsFailure'] = ApiClient.convertToType(data['dnsFailure'], 'String');
      }
      if (data.hasOwnProperty('onboarding')) {
        obj['onboarding'] = ClientDetailResponseResponseDetailOnboarding.constructFromObject(data['onboarding']);
      }
      if (data.hasOwnProperty('onboardingTime')) {
        obj['onboardingTime'] = ApiClient.convertToType(data['onboardingTime'], 'String');
      }
      if (data.hasOwnProperty('port')) {
        obj['port'] = ApiClient.convertToType(data['port'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} connectionStatus
   */
  exports.prototype['connectionStatus'] = undefined;
  /**
   * @member {String} hostType
   */
  exports.prototype['hostType'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} hostName
   */
  exports.prototype['hostName'] = undefined;
  /**
   * @member {String} hostOs
   */
  exports.prototype['hostOs'] = undefined;
  /**
   * @member {String} hostVersion
   */
  exports.prototype['hostVersion'] = undefined;
  /**
   * @member {String} subType
   */
  exports.prototype['subType'] = undefined;
  /**
   * @member {String} lastUpdated
   */
  exports.prototype['lastUpdated'] = undefined;
  /**
   * @member {Array.<module:model/ClientDetailResponseResponseDetailHealthScore>} healthScore
   */
  exports.prototype['healthScore'] = undefined;
  /**
   * @member {String} hostMac
   */
  exports.prototype['hostMac'] = undefined;
  /**
   * @member {String} hostIpV4
   */
  exports.prototype['hostIpV4'] = undefined;
  /**
   * @member {Array.<String>} hostIpV6
   */
  exports.prototype['hostIpV6'] = undefined;
  /**
   * @member {String} authType
   */
  exports.prototype['authType'] = undefined;
  /**
   * @member {String} vlanId
   */
  exports.prototype['vlanId'] = undefined;
  /**
   * @member {String} ssid
   */
  exports.prototype['ssid'] = undefined;
  /**
   * @member {String} frequency
   */
  exports.prototype['frequency'] = undefined;
  /**
   * @member {String} channel
   */
  exports.prototype['channel'] = undefined;
  /**
   * @member {String} apGroup
   */
  exports.prototype['apGroup'] = undefined;
  /**
   * @member {String} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {String} clientConnection
   */
  exports.prototype['clientConnection'] = undefined;
  /**
   * @member {Array.<String>} connectedDevice
   */
  exports.prototype['connectedDevice'] = undefined;
  /**
   * @member {String} issueCount
   */
  exports.prototype['issueCount'] = undefined;
  /**
   * @member {String} rssi
   */
  exports.prototype['rssi'] = undefined;
  /**
   * @member {String} avgRssi
   */
  exports.prototype['avgRssi'] = undefined;
  /**
   * @member {String} snr
   */
  exports.prototype['snr'] = undefined;
  /**
   * @member {String} avgSnr
   */
  exports.prototype['avgSnr'] = undefined;
  /**
   * @member {String} dataRate
   */
  exports.prototype['dataRate'] = undefined;
  /**
   * @member {String} txBytes
   */
  exports.prototype['txBytes'] = undefined;
  /**
   * @member {String} rxBytes
   */
  exports.prototype['rxBytes'] = undefined;
  /**
   * @member {String} dnsSuccess
   */
  exports.prototype['dnsSuccess'] = undefined;
  /**
   * @member {String} dnsFailure
   */
  exports.prototype['dnsFailure'] = undefined;
  /**
   * @member {module:model/ClientDetailResponseResponseDetailOnboarding} onboarding
   */
  exports.prototype['onboarding'] = undefined;
  /**
   * @member {String} onboardingTime
   */
  exports.prototype['onboardingTime'] = undefined;
  /**
   * @member {String} port
   */
  exports.prototype['port'] = undefined;



  return exports;
}));


