/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ClientDetailResponseResponseTopologyNodes = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ClientDetailResponseResponseTopologyNodes model module.
   * @module model/ClientDetailResponseResponseTopologyNodes
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ClientDetailResponseResponseTopologyNodes</code>.
   * @alias module:model/ClientDetailResponseResponseTopologyNodes
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>ClientDetailResponseResponseTopologyNodes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientDetailResponseResponseTopologyNodes} obj Optional instance to populate.
   * @return {module:model/ClientDetailResponseResponseTopologyNodes} The populated <code>ClientDetailResponseResponseTopologyNodes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('deviceType')) {
        obj['deviceType'] = ApiClient.convertToType(data['deviceType'], 'String');
      }
      if (data.hasOwnProperty('platformId')) {
        obj['platformId'] = ApiClient.convertToType(data['platformId'], 'String');
      }
      if (data.hasOwnProperty('family')) {
        obj['family'] = ApiClient.convertToType(data['family'], 'String');
      }
      if (data.hasOwnProperty('ip')) {
        obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
      }
      if (data.hasOwnProperty('softwareVersion')) {
        obj['softwareVersion'] = ApiClient.convertToType(data['softwareVersion'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('nodeType')) {
        obj['nodeType'] = ApiClient.convertToType(data['nodeType'], 'String');
      }
      if (data.hasOwnProperty('radioFrequency')) {
        obj['radioFrequency'] = ApiClient.convertToType(data['radioFrequency'], 'String');
      }
      if (data.hasOwnProperty('clients')) {
        obj['clients'] = ApiClient.convertToType(data['clients'], 'String');
      }
      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'String');
      }
      if (data.hasOwnProperty('healthScore')) {
        obj['healthScore'] = ApiClient.convertToType(data['healthScore'], 'String');
      }
      if (data.hasOwnProperty('level')) {
        obj['level'] = ApiClient.convertToType(data['level'], 'String');
      }
      if (data.hasOwnProperty('fabricGroup')) {
        obj['fabricGroup'] = ApiClient.convertToType(data['fabricGroup'], 'String');
      }
      if (data.hasOwnProperty('connectedDevice')) {
        obj['connectedDevice'] = ApiClient.convertToType(data['connectedDevice'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} deviceType
   */
  exports.prototype['deviceType'] = undefined;
  /**
   * @member {String} platformId
   */
  exports.prototype['platformId'] = undefined;
  /**
   * @member {String} family
   */
  exports.prototype['family'] = undefined;
  /**
   * @member {String} ip
   */
  exports.prototype['ip'] = undefined;
  /**
   * @member {String} softwareVersion
   */
  exports.prototype['softwareVersion'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} nodeType
   */
  exports.prototype['nodeType'] = undefined;
  /**
   * @member {String} radioFrequency
   */
  exports.prototype['radioFrequency'] = undefined;
  /**
   * @member {String} clients
   */
  exports.prototype['clients'] = undefined;
  /**
   * @member {String} count
   */
  exports.prototype['count'] = undefined;
  /**
   * @member {String} healthScore
   */
  exports.prototype['healthScore'] = undefined;
  /**
   * @member {String} level
   */
  exports.prototype['level'] = undefined;
  /**
   * @member {String} fabricGroup
   */
  exports.prototype['fabricGroup'] = undefined;
  /**
   * @member {String} connectedDevice
   */
  exports.prototype['connectedDevice'] = undefined;



  return exports;
}));


