/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeviceInnerHistoryTaskInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DeviceInnerHistoryTaskInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.DeviceInnerRunSummaryList = factory(root.Swagger.ApiClient, root.Swagger.DeviceInnerHistoryTaskInfo);
  }
}(this, function(ApiClient, DeviceInnerHistoryTaskInfo) {
  'use strict';




  /**
   * The DeviceInnerRunSummaryList model module.
   * @module model/DeviceInnerRunSummaryList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeviceInnerRunSummaryList</code>.
   * @alias module:model/DeviceInnerRunSummaryList
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>DeviceInnerRunSummaryList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInnerRunSummaryList} obj Optional instance to populate.
   * @return {module:model/DeviceInnerRunSummaryList} The populated <code>DeviceInnerRunSummaryList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], 'String');
      }
      if (data.hasOwnProperty('errorFlag')) {
        obj['errorFlag'] = ApiClient.convertToType(data['errorFlag'], 'Boolean');
      }
      if (data.hasOwnProperty('historyTaskInfo')) {
        obj['historyTaskInfo'] = DeviceInnerHistoryTaskInfo.constructFromObject(data['historyTaskInfo']);
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} details
   */
  exports.prototype['details'] = undefined;
  /**
   * @member {Boolean} errorFlag
   */
  exports.prototype['errorFlag'] = undefined;
  /**
   * @member {module:model/DeviceInnerHistoryTaskInfo} historyTaskInfo
   */
  exports.prototype['historyTaskInfo'] = undefined;
  /**
   * @member {Number} timestamp
   */
  exports.prototype['timestamp'] = undefined;



  return exports;
}));


