/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeviceInnerHistoryTaskInfoWorkItemList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DeviceInnerHistoryTaskInfoWorkItemList'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.DeviceInnerSystemResetWorkflowTasks = factory(root.Swagger.ApiClient, root.Swagger.DeviceInnerHistoryTaskInfoWorkItemList);
  }
}(this, function(ApiClient, DeviceInnerHistoryTaskInfoWorkItemList) {
  'use strict';




  /**
   * The DeviceInnerSystemResetWorkflowTasks model module.
   * @module model/DeviceInnerSystemResetWorkflowTasks
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeviceInnerSystemResetWorkflowTasks</code>.
   * @alias module:model/DeviceInnerSystemResetWorkflowTasks
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>DeviceInnerSystemResetWorkflowTasks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInnerSystemResetWorkflowTasks} obj Optional instance to populate.
   * @return {module:model/DeviceInnerSystemResetWorkflowTasks} The populated <code>DeviceInnerSystemResetWorkflowTasks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('currWorkItemIdx')) {
        obj['currWorkItemIdx'] = ApiClient.convertToType(data['currWorkItemIdx'], 'Number');
      }
      if (data.hasOwnProperty('endTime')) {
        obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Number');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('taskSeqNo')) {
        obj['taskSeqNo'] = ApiClient.convertToType(data['taskSeqNo'], 'Number');
      }
      if (data.hasOwnProperty('timeTaken')) {
        obj['timeTaken'] = ApiClient.convertToType(data['timeTaken'], 'Number');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('workItemList')) {
        obj['workItemList'] = ApiClient.convertToType(data['workItemList'], [DeviceInnerHistoryTaskInfoWorkItemList]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} currWorkItemIdx
   */
  exports.prototype['currWorkItemIdx'] = undefined;
  /**
   * @member {Number} endTime
   */
  exports.prototype['endTime'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Number} taskSeqNo
   */
  exports.prototype['taskSeqNo'] = undefined;
  /**
   * @member {Number} timeTaken
   */
  exports.prototype['timeTaken'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Array.<module:model/DeviceInnerHistoryTaskInfoWorkItemList>} workItemList
   */
  exports.prototype['workItemList'] = undefined;



  return exports;
}));


