/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.DeviceInnerDeviceInfoStackInfoStackMemberList = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeviceInnerDeviceInfoStackInfoStackMemberList model module.
   * @module model/DeviceInnerDeviceInfoStackInfoStackMemberList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DeviceInnerDeviceInfoStackInfoStackMemberList</code>.
   * @alias module:model/DeviceInnerDeviceInfoStackInfoStackMemberList
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>DeviceInnerDeviceInfoStackInfoStackMemberList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceInnerDeviceInfoStackInfoStackMemberList} obj Optional instance to populate.
   * @return {module:model/DeviceInnerDeviceInfoStackInfoStackMemberList} The populated <code>DeviceInnerDeviceInfoStackInfoStackMemberList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('hardwareVersion')) {
        obj['hardwareVersion'] = ApiClient.convertToType(data['hardwareVersion'], 'String');
      }
      if (data.hasOwnProperty('licenseLevel')) {
        obj['licenseLevel'] = ApiClient.convertToType(data['licenseLevel'], 'String');
      }
      if (data.hasOwnProperty('licenseType')) {
        obj['licenseType'] = ApiClient.convertToType(data['licenseType'], 'String');
      }
      if (data.hasOwnProperty('macAddress')) {
        obj['macAddress'] = ApiClient.convertToType(data['macAddress'], 'String');
      }
      if (data.hasOwnProperty('pid')) {
        obj['pid'] = ApiClient.convertToType(data['pid'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('serialNumber')) {
        obj['serialNumber'] = ApiClient.convertToType(data['serialNumber'], 'String');
      }
      if (data.hasOwnProperty('softwareVersion')) {
        obj['softwareVersion'] = ApiClient.convertToType(data['softwareVersion'], 'String');
      }
      if (data.hasOwnProperty('stackNumber')) {
        obj['stackNumber'] = ApiClient.convertToType(data['stackNumber'], 'Number');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('sudiSerialNumber')) {
        obj['sudiSerialNumber'] = ApiClient.convertToType(data['sudiSerialNumber'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} hardwareVersion
   */
  exports.prototype['hardwareVersion'] = undefined;
  /**
   * @member {String} licenseLevel
   */
  exports.prototype['licenseLevel'] = undefined;
  /**
   * @member {String} licenseType
   */
  exports.prototype['licenseType'] = undefined;
  /**
   * @member {String} macAddress
   */
  exports.prototype['macAddress'] = undefined;
  /**
   * @member {String} pid
   */
  exports.prototype['pid'] = undefined;
  /**
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {String} serialNumber
   */
  exports.prototype['serialNumber'] = undefined;
  /**
   * @member {String} softwareVersion
   */
  exports.prototype['softwareVersion'] = undefined;
  /**
   * @member {Number} stackNumber
   */
  exports.prototype['stackNumber'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} sudiSerialNumber
   */
  exports.prototype['sudiSerialNumber'] = undefined;



  return exports;
}));


