/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ExportDeviceDTO = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExportDeviceDTO model module.
   * @module model/ExportDeviceDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ExportDeviceDTO</code>.
   * @alias module:model/ExportDeviceDTO
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>ExportDeviceDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExportDeviceDTO} obj Optional instance to populate.
   * @return {module:model/ExportDeviceDTO} The populated <code>ExportDeviceDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceUuids')) {
        obj['deviceUuids'] = ApiClient.convertToType(data['deviceUuids'], ['String']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('operationEnum')) {
        obj['operationEnum'] = ApiClient.convertToType(data['operationEnum'], 'String');
      }
      if (data.hasOwnProperty('parameters')) {
        obj['parameters'] = ApiClient.convertToType(data['parameters'], ['String']);
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} deviceUuids
   */
  exports.prototype['deviceUuids'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/ExportDeviceDTO.OperationEnumEnum} operationEnum
   */
  exports.prototype['operationEnum'] = undefined;
  /**
   * @member {Array.<String>} parameters
   */
  exports.prototype['parameters'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;


  /**
   * Allowed values for the <code>operationEnum</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OperationEnumEnum = {
    /**
     * value: "CREDENTIALDETAILS"
     * @const
     */
    "CREDENTIALDETAILS": "CREDENTIALDETAILS",
    /**
     * value: "DEVICEDETAILS"
     * @const
     */
    "DEVICEDETAILS": "DEVICEDETAILS"  };


  return exports;
}));


