/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.FileObjectListResultResponse = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FileObjectListResultResponse model module.
   * @module model/FileObjectListResultResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FileObjectListResultResponse</code>.
   * @alias module:model/FileObjectListResultResponse
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>FileObjectListResultResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileObjectListResultResponse} obj Optional instance to populate.
   * @return {module:model/FileObjectListResultResponse} The populated <code>FileObjectListResultResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attributeInfo')) {
        obj['attributeInfo'] = ApiClient.convertToType(data['attributeInfo'], Object);
      }
      if (data.hasOwnProperty('downloadPath')) {
        obj['downloadPath'] = ApiClient.convertToType(data['downloadPath'], 'String');
      }
      if (data.hasOwnProperty('encrypted')) {
        obj['encrypted'] = ApiClient.convertToType(data['encrypted'], 'Boolean');
      }
      if (data.hasOwnProperty('fileFormat')) {
        obj['fileFormat'] = ApiClient.convertToType(data['fileFormat'], 'String');
      }
      if (data.hasOwnProperty('fileSize')) {
        obj['fileSize'] = ApiClient.convertToType(data['fileSize'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('md5Checksum')) {
        obj['md5Checksum'] = ApiClient.convertToType(data['md5Checksum'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('nameSpace')) {
        obj['nameSpace'] = ApiClient.convertToType(data['nameSpace'], 'String');
      }
      if (data.hasOwnProperty('sftpServerList')) {
        obj['sftpServerList'] = ApiClient.convertToType(data['sftpServerList'], [Object]);
      }
      if (data.hasOwnProperty('sha1Checksum')) {
        obj['sha1Checksum'] = ApiClient.convertToType(data['sha1Checksum'], 'String');
      }
      if (data.hasOwnProperty('taskId')) {
        obj['taskId'] = ApiClient.convertToType(data['taskId'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Object} attributeInfo
   */
  exports.prototype['attributeInfo'] = undefined;
  /**
   * @member {String} downloadPath
   */
  exports.prototype['downloadPath'] = undefined;
  /**
   * @member {Boolean} encrypted
   */
  exports.prototype['encrypted'] = undefined;
  /**
   * @member {String} fileFormat
   */
  exports.prototype['fileFormat'] = undefined;
  /**
   * @member {String} fileSize
   */
  exports.prototype['fileSize'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} md5Checksum
   */
  exports.prototype['md5Checksum'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} nameSpace
   */
  exports.prototype['nameSpace'] = undefined;
  /**
   * @member {Array.<Object>} sftpServerList
   */
  exports.prototype['sftpServerList'] = undefined;
  /**
   * @member {String} sha1Checksum
   */
  exports.prototype['sha1Checksum'] = undefined;
  /**
   * @member {Object} taskId
   */
  exports.prototype['taskId'] = undefined;



  return exports;
}));


