/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.FlowAnalysisRequest = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The FlowAnalysisRequest model module.
   * @module model/FlowAnalysisRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>FlowAnalysisRequest</code>.
   * @alias module:model/FlowAnalysisRequest
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>FlowAnalysisRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlowAnalysisRequest} obj Optional instance to populate.
   * @return {module:model/FlowAnalysisRequest} The populated <code>FlowAnalysisRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('controlPath')) {
        obj['controlPath'] = ApiClient.convertToType(data['controlPath'], 'Boolean');
      }
      if (data.hasOwnProperty('destIP')) {
        obj['destIP'] = ApiClient.convertToType(data['destIP'], 'String');
      }
      if (data.hasOwnProperty('destPort')) {
        obj['destPort'] = ApiClient.convertToType(data['destPort'], 'String');
      }
      if (data.hasOwnProperty('inclusions')) {
        obj['inclusions'] = ApiClient.convertToType(data['inclusions'], ['String']);
      }
      if (data.hasOwnProperty('periodicRefresh')) {
        obj['periodicRefresh'] = ApiClient.convertToType(data['periodicRefresh'], 'Boolean');
      }
      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
      if (data.hasOwnProperty('sourceIP')) {
        obj['sourceIP'] = ApiClient.convertToType(data['sourceIP'], 'String');
      }
      if (data.hasOwnProperty('sourcePort')) {
        obj['sourcePort'] = ApiClient.convertToType(data['sourcePort'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} controlPath
   */
  exports.prototype['controlPath'] = undefined;
  /**
   * @member {String} destIP
   */
  exports.prototype['destIP'] = undefined;
  /**
   * @member {String} destPort
   */
  exports.prototype['destPort'] = undefined;
  /**
   * @member {Array.<String>} inclusions
   */
  exports.prototype['inclusions'] = undefined;
  /**
   * @member {Boolean} periodicRefresh
   */
  exports.prototype['periodicRefresh'] = undefined;
  /**
   * @member {String} protocol
   */
  exports.prototype['protocol'] = undefined;
  /**
   * @member {String} sourceIP
   */
  exports.prototype['sourceIP'] = undefined;
  /**
   * @member {String} sourcePort
   */
  exports.prototype['sourcePort'] = undefined;



  return exports;
}));


