/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ImageImportFromUrlDTOInner'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ImageImportFromUrlDTOInner'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ImageImportFromUrlDTO = factory(root.Swagger.ApiClient, root.Swagger.ImageImportFromUrlDTOInner);
  }
}(this, function(ApiClient, ImageImportFromUrlDTOInner) {
  'use strict';




  /**
   * The ImageImportFromUrlDTO model module.
   * @module model/ImageImportFromUrlDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ImageImportFromUrlDTO</code>.
   * @alias module:model/ImageImportFromUrlDTO
   * @class
   * @extends Array
   */
  var exports = function() {
    var _this = this;
    _this = new Array();
    Object.setPrototypeOf(_this, exports);

    return _this;
  };

  /**
   * Constructs a <code>ImageImportFromUrlDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageImportFromUrlDTO} obj Optional instance to populate.
   * @return {module:model/ImageImportFromUrlDTO} The populated <code>ImageImportFromUrlDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'ImageImportFromUrlDTOInner');

    }
    return obj;
  }




  return exports;
}));


