/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ImageInfoListResponseApplicableDevicesForImage = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageInfoListResponseApplicableDevicesForImage model module.
   * @module model/ImageInfoListResponseApplicableDevicesForImage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ImageInfoListResponseApplicableDevicesForImage</code>.
   * @alias module:model/ImageInfoListResponseApplicableDevicesForImage
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ImageInfoListResponseApplicableDevicesForImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageInfoListResponseApplicableDevicesForImage} obj Optional instance to populate.
   * @return {module:model/ImageInfoListResponseApplicableDevicesForImage} The populated <code>ImageInfoListResponseApplicableDevicesForImage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mdfId')) {
        obj['mdfId'] = ApiClient.convertToType(data['mdfId'], 'String');
      }
      if (data.hasOwnProperty('productId')) {
        obj['productId'] = ApiClient.convertToType(data['productId'], ['String']);
      }
      if (data.hasOwnProperty('productName')) {
        obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} mdfId
   */
  exports.prototype['mdfId'] = undefined;
  /**
   * @member {Array.<String>} productId
   */
  exports.prototype['productId'] = undefined;
  /**
   * @member {String} productName
   */
  exports.prototype['productName'] = undefined;



  return exports;
}));


