/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ImageInfoListResponseProfileInfo = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageInfoListResponseProfileInfo model module.
   * @module model/ImageInfoListResponseProfileInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ImageInfoListResponseProfileInfo</code>.
   * @alias module:model/ImageInfoListResponseProfileInfo
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>ImageInfoListResponseProfileInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageInfoListResponseProfileInfo} obj Optional instance to populate.
   * @return {module:model/ImageInfoListResponseProfileInfo} The populated <code>ImageInfoListResponseProfileInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('extendedAttributes')) {
        obj['extendedAttributes'] = ApiClient.convertToType(data['extendedAttributes'], Object);
      }
      if (data.hasOwnProperty('memory')) {
        obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
      }
      if (data.hasOwnProperty('productType')) {
        obj['productType'] = ApiClient.convertToType(data['productType'], 'String');
      }
      if (data.hasOwnProperty('profileName')) {
        obj['profileName'] = ApiClient.convertToType(data['profileName'], 'String');
      }
      if (data.hasOwnProperty('shares')) {
        obj['shares'] = ApiClient.convertToType(data['shares'], 'Number');
      }
      if (data.hasOwnProperty('vCpu')) {
        obj['vCpu'] = ApiClient.convertToType(data['vCpu'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Object} extendedAttributes
   */
  exports.prototype['extendedAttributes'] = undefined;
  /**
   * @member {Number} memory
   */
  exports.prototype['memory'] = undefined;
  /**
   * @member {String} productType
   */
  exports.prototype['productType'] = undefined;
  /**
   * @member {String} profileName
   */
  exports.prototype['profileName'] = undefined;
  /**
   * @member {Number} shares
   */
  exports.prototype['shares'] = undefined;
  /**
   * @member {Number} vCpu
   */
  exports.prototype['vCpu'] = undefined;



  return exports;
}));


