/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InventoryDeviceInfoUpdateMgmtIPaddressList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InventoryDeviceInfoUpdateMgmtIPaddressList'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.InventoryDeviceInfo = factory(root.Swagger.ApiClient, root.Swagger.InventoryDeviceInfoUpdateMgmtIPaddressList);
  }
}(this, function(ApiClient, InventoryDeviceInfoUpdateMgmtIPaddressList) {
  'use strict';




  /**
   * The InventoryDeviceInfo model module.
   * @module model/InventoryDeviceInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InventoryDeviceInfo</code>.
   * @alias module:model/InventoryDeviceInfo
   * @class
   */
  var exports = function() {
    var _this = this;




























  };

  /**
   * Constructs a <code>InventoryDeviceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InventoryDeviceInfo} obj Optional instance to populate.
   * @return {module:model/InventoryDeviceInfo} The populated <code>InventoryDeviceInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cliTransport')) {
        obj['cliTransport'] = ApiClient.convertToType(data['cliTransport'], 'String');
      }
      if (data.hasOwnProperty('computeDevice')) {
        obj['computeDevice'] = ApiClient.convertToType(data['computeDevice'], 'Boolean');
      }
      if (data.hasOwnProperty('enablePassword')) {
        obj['enablePassword'] = ApiClient.convertToType(data['enablePassword'], 'String');
      }
      if (data.hasOwnProperty('extendedDiscoveryInfo')) {
        obj['extendedDiscoveryInfo'] = ApiClient.convertToType(data['extendedDiscoveryInfo'], 'String');
      }
      if (data.hasOwnProperty('httpPassword')) {
        obj['httpPassword'] = ApiClient.convertToType(data['httpPassword'], 'String');
      }
      if (data.hasOwnProperty('httpPort')) {
        obj['httpPort'] = ApiClient.convertToType(data['httpPort'], 'String');
      }
      if (data.hasOwnProperty('httpSecure')) {
        obj['httpSecure'] = ApiClient.convertToType(data['httpSecure'], 'Boolean');
      }
      if (data.hasOwnProperty('httpUserName')) {
        obj['httpUserName'] = ApiClient.convertToType(data['httpUserName'], 'String');
      }
      if (data.hasOwnProperty('ipAddress')) {
        obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], ['String']);
      }
      if (data.hasOwnProperty('merakiOrgId')) {
        obj['merakiOrgId'] = ApiClient.convertToType(data['merakiOrgId'], ['String']);
      }
      if (data.hasOwnProperty('netconfPort')) {
        obj['netconfPort'] = ApiClient.convertToType(data['netconfPort'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('serialNumber')) {
        obj['serialNumber'] = ApiClient.convertToType(data['serialNumber'], 'String');
      }
      if (data.hasOwnProperty('snmpAuthPassphrase')) {
        obj['snmpAuthPassphrase'] = ApiClient.convertToType(data['snmpAuthPassphrase'], 'String');
      }
      if (data.hasOwnProperty('snmpAuthProtocol')) {
        obj['snmpAuthProtocol'] = ApiClient.convertToType(data['snmpAuthProtocol'], 'String');
      }
      if (data.hasOwnProperty('snmpMode')) {
        obj['snmpMode'] = ApiClient.convertToType(data['snmpMode'], 'String');
      }
      if (data.hasOwnProperty('snmpPrivPassphrase')) {
        obj['snmpPrivPassphrase'] = ApiClient.convertToType(data['snmpPrivPassphrase'], 'String');
      }
      if (data.hasOwnProperty('snmpPrivProtocol')) {
        obj['snmpPrivProtocol'] = ApiClient.convertToType(data['snmpPrivProtocol'], 'String');
      }
      if (data.hasOwnProperty('snmpROCommunity')) {
        obj['snmpROCommunity'] = ApiClient.convertToType(data['snmpROCommunity'], 'String');
      }
      if (data.hasOwnProperty('snmpRWCommunity')) {
        obj['snmpRWCommunity'] = ApiClient.convertToType(data['snmpRWCommunity'], 'String');
      }
      if (data.hasOwnProperty('snmpRetry')) {
        obj['snmpRetry'] = ApiClient.convertToType(data['snmpRetry'], 'Number');
      }
      if (data.hasOwnProperty('snmpTimeout')) {
        obj['snmpTimeout'] = ApiClient.convertToType(data['snmpTimeout'], 'Number');
      }
      if (data.hasOwnProperty('snmpUserName')) {
        obj['snmpUserName'] = ApiClient.convertToType(data['snmpUserName'], 'String');
      }
      if (data.hasOwnProperty('snmpVersion')) {
        obj['snmpVersion'] = ApiClient.convertToType(data['snmpVersion'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('updateMgmtIPaddressList')) {
        obj['updateMgmtIPaddressList'] = ApiClient.convertToType(data['updateMgmtIPaddressList'], [InventoryDeviceInfoUpdateMgmtIPaddressList]);
      }
      if (data.hasOwnProperty('userName')) {
        obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} cliTransport
   */
  exports.prototype['cliTransport'] = undefined;
  /**
   * @member {Boolean} computeDevice
   */
  exports.prototype['computeDevice'] = undefined;
  /**
   * @member {String} enablePassword
   */
  exports.prototype['enablePassword'] = undefined;
  /**
   * @member {String} extendedDiscoveryInfo
   */
  exports.prototype['extendedDiscoveryInfo'] = undefined;
  /**
   * @member {String} httpPassword
   */
  exports.prototype['httpPassword'] = undefined;
  /**
   * @member {String} httpPort
   */
  exports.prototype['httpPort'] = undefined;
  /**
   * @member {Boolean} httpSecure
   */
  exports.prototype['httpSecure'] = undefined;
  /**
   * @member {String} httpUserName
   */
  exports.prototype['httpUserName'] = undefined;
  /**
   * @member {Array.<String>} ipAddress
   */
  exports.prototype['ipAddress'] = undefined;
  /**
   * @member {Array.<String>} merakiOrgId
   */
  exports.prototype['merakiOrgId'] = undefined;
  /**
   * @member {String} netconfPort
   */
  exports.prototype['netconfPort'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {String} serialNumber
   */
  exports.prototype['serialNumber'] = undefined;
  /**
   * @member {String} snmpAuthPassphrase
   */
  exports.prototype['snmpAuthPassphrase'] = undefined;
  /**
   * @member {String} snmpAuthProtocol
   */
  exports.prototype['snmpAuthProtocol'] = undefined;
  /**
   * @member {String} snmpMode
   */
  exports.prototype['snmpMode'] = undefined;
  /**
   * @member {String} snmpPrivPassphrase
   */
  exports.prototype['snmpPrivPassphrase'] = undefined;
  /**
   * @member {String} snmpPrivProtocol
   */
  exports.prototype['snmpPrivProtocol'] = undefined;
  /**
   * @member {String} snmpROCommunity
   */
  exports.prototype['snmpROCommunity'] = undefined;
  /**
   * @member {String} snmpRWCommunity
   */
  exports.prototype['snmpRWCommunity'] = undefined;
  /**
   * @member {Number} snmpRetry
   */
  exports.prototype['snmpRetry'] = undefined;
  /**
   * @member {Number} snmpTimeout
   */
  exports.prototype['snmpTimeout'] = undefined;
  /**
   * @member {String} snmpUserName
   */
  exports.prototype['snmpUserName'] = undefined;
  /**
   * @member {String} snmpVersion
   */
  exports.prototype['snmpVersion'] = undefined;
  /**
   * @member {module:model/InventoryDeviceInfo.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Array.<module:model/InventoryDeviceInfoUpdateMgmtIPaddressList>} updateMgmtIPaddressList
   */
  exports.prototype['updateMgmtIPaddressList'] = undefined;
  /**
   * @member {String} userName
   */
  exports.prototype['userName'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "COMPUTE_DEVICE"
     * @const
     */
    "COMPUTE_DEVICE": "COMPUTE_DEVICE",
    /**
     * value: "MERAKI_DASHBOARD"
     * @const
     */
    "MERAKI_DASHBOARD": "MERAKI_DASHBOARD",
    /**
     * value: "NETWORK_DEVICE"
     * @const
     */
    "NETWORK_DEVICE": "NETWORK_DEVICE",
    /**
     * value: "NODATACHANGE"
     * @const
     */
    "NODATACHANGE": "NODATACHANGE"  };


  return exports;
}));


