/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.PathResponseResultResponseDeviceStatisticsCpuStatistics = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PathResponseResultResponseDeviceStatisticsCpuStatistics model module.
   * @module model/PathResponseResultResponseDeviceStatisticsCpuStatistics
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PathResponseResultResponseDeviceStatisticsCpuStatistics</code>.
   * @alias module:model/PathResponseResultResponseDeviceStatisticsCpuStatistics
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PathResponseResultResponseDeviceStatisticsCpuStatistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PathResponseResultResponseDeviceStatisticsCpuStatistics} obj Optional instance to populate.
   * @return {module:model/PathResponseResultResponseDeviceStatisticsCpuStatistics} The populated <code>PathResponseResultResponseDeviceStatisticsCpuStatistics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fiveMinUsageInPercentage')) {
        obj['fiveMinUsageInPercentage'] = ApiClient.convertToType(data['fiveMinUsageInPercentage'], 'Number');
      }
      if (data.hasOwnProperty('fiveSecsUsageInPercentage')) {
        obj['fiveSecsUsageInPercentage'] = ApiClient.convertToType(data['fiveSecsUsageInPercentage'], 'Number');
      }
      if (data.hasOwnProperty('oneMinUsageInPercentage')) {
        obj['oneMinUsageInPercentage'] = ApiClient.convertToType(data['oneMinUsageInPercentage'], 'Number');
      }
      if (data.hasOwnProperty('refreshedAt')) {
        obj['refreshedAt'] = ApiClient.convertToType(data['refreshedAt'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} fiveMinUsageInPercentage
   */
  exports.prototype['fiveMinUsageInPercentage'] = undefined;
  /**
   * @member {Number} fiveSecsUsageInPercentage
   */
  exports.prototype['fiveSecsUsageInPercentage'] = undefined;
  /**
   * @member {Number} oneMinUsageInPercentage
   */
  exports.prototype['oneMinUsageInPercentage'] = undefined;
  /**
   * @member {Number} refreshedAt
   */
  exports.prototype['refreshedAt'] = undefined;



  return exports;
}));


