/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FlowAnalysisListOutputResponse', 'model/PathResponseResultResponseDetailedStatus', 'model/PathResponseResultResponseNetworkElements', 'model/PathResponseResultResponseNetworkElementsInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FlowAnalysisListOutputResponse'), require('./PathResponseResultResponseDetailedStatus'), require('./PathResponseResultResponseNetworkElements'), require('./PathResponseResultResponseNetworkElementsInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.PathResponseResultResponse = factory(root.Swagger.ApiClient, root.Swagger.FlowAnalysisListOutputResponse, root.Swagger.PathResponseResultResponseDetailedStatus, root.Swagger.PathResponseResultResponseNetworkElements, root.Swagger.PathResponseResultResponseNetworkElementsInfo);
  }
}(this, function(ApiClient, FlowAnalysisListOutputResponse, PathResponseResultResponseDetailedStatus, PathResponseResultResponseNetworkElements, PathResponseResultResponseNetworkElementsInfo) {
  'use strict';




  /**
   * The PathResponseResultResponse model module.
   * @module model/PathResponseResultResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PathResponseResultResponse</code>.
   * @alias module:model/PathResponseResultResponse
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PathResponseResultResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PathResponseResultResponse} obj Optional instance to populate.
   * @return {module:model/PathResponseResultResponse} The populated <code>PathResponseResultResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('detailedStatus')) {
        obj['detailedStatus'] = PathResponseResultResponseDetailedStatus.constructFromObject(data['detailedStatus']);
      }
      if (data.hasOwnProperty('lastUpdate')) {
        obj['lastUpdate'] = ApiClient.convertToType(data['lastUpdate'], 'String');
      }
      if (data.hasOwnProperty('networkElements')) {
        obj['networkElements'] = ApiClient.convertToType(data['networkElements'], [PathResponseResultResponseNetworkElements]);
      }
      if (data.hasOwnProperty('networkElementsInfo')) {
        obj['networkElementsInfo'] = ApiClient.convertToType(data['networkElementsInfo'], [PathResponseResultResponseNetworkElementsInfo]);
      }
      if (data.hasOwnProperty('properties')) {
        obj['properties'] = ApiClient.convertToType(data['properties'], ['String']);
      }
      if (data.hasOwnProperty('request')) {
        obj['request'] = FlowAnalysisListOutputResponse.constructFromObject(data['request']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PathResponseResultResponseDetailedStatus} detailedStatus
   */
  exports.prototype['detailedStatus'] = undefined;
  /**
   * @member {String} lastUpdate
   */
  exports.prototype['lastUpdate'] = undefined;
  /**
   * @member {Array.<module:model/PathResponseResultResponseNetworkElements>} networkElements
   */
  exports.prototype['networkElements'] = undefined;
  /**
   * @member {Array.<module:model/PathResponseResultResponseNetworkElementsInfo>} networkElementsInfo
   */
  exports.prototype['networkElementsInfo'] = undefined;
  /**
   * @member {Array.<String>} properties
   */
  exports.prototype['properties'] = undefined;
  /**
   * @member {module:model/FlowAnalysisListOutputResponse} request
   */
  exports.prototype['request'] = undefined;



  return exports;
}));


