/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.PathResponseResultResponseAccuracyList = factory(root.Swagger.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PathResponseResultResponseAccuracyList model module.
   * @module model/PathResponseResultResponseAccuracyList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PathResponseResultResponseAccuracyList</code>.
   * @alias module:model/PathResponseResultResponseAccuracyList
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PathResponseResultResponseAccuracyList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PathResponseResultResponseAccuracyList} obj Optional instance to populate.
   * @return {module:model/PathResponseResultResponseAccuracyList} The populated <code>PathResponseResultResponseAccuracyList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('percent')) {
        obj['percent'] = ApiClient.convertToType(data['percent'], 'Number');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} percent
   */
  exports.prototype['percent'] = undefined;
  /**
   * @member {String} reason
   */
  exports.prototype['reason'] = undefined;



  return exports;
}));


