/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PathResponseResultResponseAccuracyList', 'model/PathResponseResultResponseDetailedStatus', 'model/PathResponseResultResponseDeviceStatistics', 'model/PathResponseResultResponseEgressInterface', 'model/PathResponseResultResponseFlexConnect', 'model/PathResponseResultResponsePerfMonStatistics'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PathResponseResultResponseAccuracyList'), require('./PathResponseResultResponseDetailedStatus'), require('./PathResponseResultResponseDeviceStatistics'), require('./PathResponseResultResponseEgressInterface'), require('./PathResponseResultResponseFlexConnect'), require('./PathResponseResultResponsePerfMonStatistics'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.PathResponseResultResponseNetworkElementsInfo = factory(root.Swagger.ApiClient, root.Swagger.PathResponseResultResponseAccuracyList, root.Swagger.PathResponseResultResponseDetailedStatus, root.Swagger.PathResponseResultResponseDeviceStatistics, root.Swagger.PathResponseResultResponseEgressInterface, root.Swagger.PathResponseResultResponseFlexConnect, root.Swagger.PathResponseResultResponsePerfMonStatistics);
  }
}(this, function(ApiClient, PathResponseResultResponseAccuracyList, PathResponseResultResponseDetailedStatus, PathResponseResultResponseDeviceStatistics, PathResponseResultResponseEgressInterface, PathResponseResultResponseFlexConnect, PathResponseResultResponsePerfMonStatistics) {
  'use strict';




  /**
   * The PathResponseResultResponseNetworkElementsInfo model module.
   * @module model/PathResponseResultResponseNetworkElementsInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PathResponseResultResponseNetworkElementsInfo</code>.
   * @alias module:model/PathResponseResultResponseNetworkElementsInfo
   * @class
   */
  var exports = function() {
    var _this = this;





















  };

  /**
   * Constructs a <code>PathResponseResultResponseNetworkElementsInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PathResponseResultResponseNetworkElementsInfo} obj Optional instance to populate.
   * @return {module:model/PathResponseResultResponseNetworkElementsInfo} The populated <code>PathResponseResultResponseNetworkElementsInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accuracyList')) {
        obj['accuracyList'] = ApiClient.convertToType(data['accuracyList'], [PathResponseResultResponseAccuracyList]);
      }
      if (data.hasOwnProperty('detailedStatus')) {
        obj['detailedStatus'] = PathResponseResultResponseDetailedStatus.constructFromObject(data['detailedStatus']);
      }
      if (data.hasOwnProperty('deviceStatistics')) {
        obj['deviceStatistics'] = PathResponseResultResponseDeviceStatistics.constructFromObject(data['deviceStatistics']);
      }
      if (data.hasOwnProperty('deviceStatsCollection')) {
        obj['deviceStatsCollection'] = ApiClient.convertToType(data['deviceStatsCollection'], 'String');
      }
      if (data.hasOwnProperty('deviceStatsCollectionFailureReason')) {
        obj['deviceStatsCollectionFailureReason'] = ApiClient.convertToType(data['deviceStatsCollectionFailureReason'], 'String');
      }
      if (data.hasOwnProperty('egressInterface')) {
        obj['egressInterface'] = PathResponseResultResponseEgressInterface.constructFromObject(data['egressInterface']);
      }
      if (data.hasOwnProperty('flexConnect')) {
        obj['flexConnect'] = PathResponseResultResponseFlexConnect.constructFromObject(data['flexConnect']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('ingressInterface')) {
        obj['ingressInterface'] = PathResponseResultResponseEgressInterface.constructFromObject(data['ingressInterface']);
      }
      if (data.hasOwnProperty('ip')) {
        obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
      }
      if (data.hasOwnProperty('linkInformationSource')) {
        obj['linkInformationSource'] = ApiClient.convertToType(data['linkInformationSource'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('perfMonCollection')) {
        obj['perfMonCollection'] = ApiClient.convertToType(data['perfMonCollection'], 'String');
      }
      if (data.hasOwnProperty('perfMonCollectionFailureReason')) {
        obj['perfMonCollectionFailureReason'] = ApiClient.convertToType(data['perfMonCollectionFailureReason'], 'String');
      }
      if (data.hasOwnProperty('perfMonitorStatistics')) {
        obj['perfMonitorStatistics'] = ApiClient.convertToType(data['perfMonitorStatistics'], [PathResponseResultResponsePerfMonStatistics]);
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('ssid')) {
        obj['ssid'] = ApiClient.convertToType(data['ssid'], 'String');
      }
      if (data.hasOwnProperty('tunnels')) {
        obj['tunnels'] = ApiClient.convertToType(data['tunnels'], ['String']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('wlanId')) {
        obj['wlanId'] = ApiClient.convertToType(data['wlanId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PathResponseResultResponseAccuracyList>} accuracyList
   */
  exports.prototype['accuracyList'] = undefined;
  /**
   * @member {module:model/PathResponseResultResponseDetailedStatus} detailedStatus
   */
  exports.prototype['detailedStatus'] = undefined;
  /**
   * @member {module:model/PathResponseResultResponseDeviceStatistics} deviceStatistics
   */
  exports.prototype['deviceStatistics'] = undefined;
  /**
   * @member {String} deviceStatsCollection
   */
  exports.prototype['deviceStatsCollection'] = undefined;
  /**
   * @member {String} deviceStatsCollectionFailureReason
   */
  exports.prototype['deviceStatsCollectionFailureReason'] = undefined;
  /**
   * @member {module:model/PathResponseResultResponseEgressInterface} egressInterface
   */
  exports.prototype['egressInterface'] = undefined;
  /**
   * @member {module:model/PathResponseResultResponseFlexConnect} flexConnect
   */
  exports.prototype['flexConnect'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {module:model/PathResponseResultResponseEgressInterface} ingressInterface
   */
  exports.prototype['ingressInterface'] = undefined;
  /**
   * @member {String} ip
   */
  exports.prototype['ip'] = undefined;
  /**
   * @member {String} linkInformationSource
   */
  exports.prototype['linkInformationSource'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} perfMonCollection
   */
  exports.prototype['perfMonCollection'] = undefined;
  /**
   * @member {String} perfMonCollectionFailureReason
   */
  exports.prototype['perfMonCollectionFailureReason'] = undefined;
  /**
   * @member {Array.<module:model/PathResponseResultResponsePerfMonStatistics>} perfMonitorStatistics
   */
  exports.prototype['perfMonitorStatistics'] = undefined;
  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {String} ssid
   */
  exports.prototype['ssid'] = undefined;
  /**
   * @member {Array.<String>} tunnels
   */
  exports.prototype['tunnels'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} wlanId
   */
  exports.prototype['wlanId'] = undefined;



  return exports;
}));


