/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis = factory(root.Swagger.ApiClient, root.Swagger.PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces);
  }
}(this, function(ApiClient, PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces) {
  'use strict';




  /**
   * The PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis model module.
   * @module model/PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis</code>.
   * @alias module:model/PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis} obj Optional instance to populate.
   * @return {module:model/PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis} The populated <code>PathResponseResultResponseEgressPhysicalInterfaceAclAnalysis</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('aclName')) {
        obj['aclName'] = ApiClient.convertToType(data['aclName'], 'String');
      }
      if (data.hasOwnProperty('matchingAces')) {
        obj['matchingAces'] = ApiClient.convertToType(data['matchingAces'], [PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces]);
      }
      if (data.hasOwnProperty('result')) {
        obj['result'] = ApiClient.convertToType(data['result'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} aclName
   */
  exports.prototype['aclName'] = undefined;
  /**
   * @member {Array.<module:model/PathResponseResultResponseEgressPhysicalInterfaceAclAnalysisMatchingAces>} matchingAces
   */
  exports.prototype['matchingAces'] = undefined;
  /**
   * @member {String} result
   */
  exports.prototype['result'] = undefined;



  return exports;
}));


