/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResetRequestDeviceResetList'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResetRequestDeviceResetList'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.ResetRequest = factory(root.Swagger.ApiClient, root.Swagger.ResetRequestDeviceResetList);
  }
}(this, function(ApiClient, ResetRequestDeviceResetList) {
  'use strict';




  /**
   * The ResetRequest model module.
   * @module model/ResetRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResetRequest</code>.
   * @alias module:model/ResetRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ResetRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResetRequest} obj Optional instance to populate.
   * @return {module:model/ResetRequest} The populated <code>ResetRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceResetList')) {
        obj['deviceResetList'] = ApiClient.convertToType(data['deviceResetList'], [ResetRequestDeviceResetList]);
      }
      if (data.hasOwnProperty('projectId')) {
        obj['projectId'] = ApiClient.convertToType(data['projectId'], 'String');
      }
      if (data.hasOwnProperty('workflowId')) {
        obj['workflowId'] = ApiClient.convertToType(data['workflowId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ResetRequestDeviceResetList>} deviceResetList
   */
  exports.prototype['deviceResetList'] = undefined;
  /**
   * @member {String} projectId
   */
  exports.prototype['projectId'] = undefined;
  /**
   * @member {String} workflowId
   */
  exports.prototype['workflowId'] = undefined;



  return exports;
}));


