/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TemplateDeploymentStatusDTODevices'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TemplateDeploymentStatusDTODevices'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.TemplateDeploymentStatusDTO = factory(root.Swagger.ApiClient, root.Swagger.TemplateDeploymentStatusDTODevices);
  }
}(this, function(ApiClient, TemplateDeploymentStatusDTODevices) {
  'use strict';




  /**
   * The TemplateDeploymentStatusDTO model module.
   * @module model/TemplateDeploymentStatusDTO
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TemplateDeploymentStatusDTO</code>.
   * @alias module:model/TemplateDeploymentStatusDTO
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>TemplateDeploymentStatusDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemplateDeploymentStatusDTO} obj Optional instance to populate.
   * @return {module:model/TemplateDeploymentStatusDTO} The populated <code>TemplateDeploymentStatusDTO</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deploymentId')) {
        obj['deploymentId'] = ApiClient.convertToType(data['deploymentId'], 'String');
      }
      if (data.hasOwnProperty('deploymentName')) {
        obj['deploymentName'] = ApiClient.convertToType(data['deploymentName'], 'String');
      }
      if (data.hasOwnProperty('devices')) {
        obj['devices'] = ApiClient.convertToType(data['devices'], [TemplateDeploymentStatusDTODevices]);
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
      }
      if (data.hasOwnProperty('endTime')) {
        obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
      }
      if (data.hasOwnProperty('projectName')) {
        obj['projectName'] = ApiClient.convertToType(data['projectName'], 'String');
      }
      if (data.hasOwnProperty('startTime')) {
        obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('templateName')) {
        obj['templateName'] = ApiClient.convertToType(data['templateName'], 'String');
      }
      if (data.hasOwnProperty('templateVersion')) {
        obj['templateVersion'] = ApiClient.convertToType(data['templateVersion'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} deploymentId
   */
  exports.prototype['deploymentId'] = undefined;
  /**
   * @member {String} deploymentName
   */
  exports.prototype['deploymentName'] = undefined;
  /**
   * @member {Array.<module:model/TemplateDeploymentStatusDTODevices>} devices
   */
  exports.prototype['devices'] = undefined;
  /**
   * @member {String} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {String} endTime
   */
  exports.prototype['endTime'] = undefined;
  /**
   * @member {String} projectName
   */
  exports.prototype['projectName'] = undefined;
  /**
   * @member {String} startTime
   */
  exports.prototype['startTime'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} templateName
   */
  exports.prototype['templateName'] = undefined;
  /**
   * @member {String} templateVersion
   */
  exports.prototype['templateVersion'] = undefined;



  return exports;
}));


