/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TemplateDeploymentInfoTargetInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TemplateDeploymentInfoTargetInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Swagger) {
      root.Swagger = {};
    }
    root.Swagger.TemplateDeploymentInfo = factory(root.Swagger.ApiClient, root.Swagger.TemplateDeploymentInfoTargetInfo);
  }
}(this, function(ApiClient, TemplateDeploymentInfoTargetInfo) {
  'use strict';




  /**
   * The TemplateDeploymentInfo model module.
   * @module model/TemplateDeploymentInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TemplateDeploymentInfo</code>.
   * @alias module:model/TemplateDeploymentInfo
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TemplateDeploymentInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TemplateDeploymentInfo} obj Optional instance to populate.
   * @return {module:model/TemplateDeploymentInfo} The populated <code>TemplateDeploymentInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('targetInfo')) {
        obj['targetInfo'] = ApiClient.convertToType(data['targetInfo'], [TemplateDeploymentInfoTargetInfo]);
      }
      if (data.hasOwnProperty('templateId')) {
        obj['templateId'] = ApiClient.convertToType(data['templateId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/TemplateDeploymentInfoTargetInfo>} targetInfo
   */
  exports.prototype['targetInfo'] = undefined;
  /**
   * @member {String} templateId
   */
  exports.prototype['templateId'] = undefined;



  return exports;
}));


