/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.TemplateProgrammerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateProgrammerApi', function() {
    describe('deleteTemplateProgrammerProjectByProjectId', function() {
      it('should call deleteTemplateProgrammerProjectByProjectId successfully', function(done) {
        //uncomment below and update the code to test deleteTemplateProgrammerProjectByProjectId
        //instance.deleteTemplateProgrammerProjectByProjectId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTemplateProgrammerTemplateByTemplateId', function() {
      it('should call deleteTemplateProgrammerTemplateByTemplateId successfully', function(done) {
        //uncomment below and update the code to test deleteTemplateProgrammerTemplateByTemplateId
        //instance.deleteTemplateProgrammerTemplateByTemplateId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemplateProgrammerProject', function() {
      it('should call getTemplateProgrammerProject successfully', function(done) {
        //uncomment below and update the code to test getTemplateProgrammerProject
        //instance.getTemplateProgrammerProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemplateProgrammerTemplate', function() {
      it('should call getTemplateProgrammerTemplate successfully', function(done) {
        //uncomment below and update the code to test getTemplateProgrammerTemplate
        //instance.getTemplateProgrammerTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemplateProgrammerTemplateDeployStatusByDeploymentId', function() {
      it('should call getTemplateProgrammerTemplateDeployStatusByDeploymentId successfully', function(done) {
        //uncomment below and update the code to test getTemplateProgrammerTemplateDeployStatusByDeploymentId
        //instance.getTemplateProgrammerTemplateDeployStatusByDeploymentId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemplateProgrammerTemplateVersionByTempleteId', function() {
      it('should call getTemplateProgrammerTemplateVersionByTempleteId successfully', function(done) {
        //uncomment below and update the code to test getTemplateProgrammerTemplateVersionByTempleteId
        //instance.getTemplateProgrammerTemplateVersionByTempleteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTemplateProgrammerProject', function() {
      it('should call postTemplateProgrammerProject successfully', function(done) {
        //uncomment below and update the code to test postTemplateProgrammerProject
        //instance.postTemplateProgrammerProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTemplateProgrammerProjectTemplateByProjectId', function() {
      it('should call postTemplateProgrammerProjectTemplateByProjectId successfully', function(done) {
        //uncomment below and update the code to test postTemplateProgrammerProjectTemplateByProjectId
        //instance.postTemplateProgrammerProjectTemplateByProjectId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTemplateProgrammerTemplateDeploy', function() {
      it('should call postTemplateProgrammerTemplateDeploy successfully', function(done) {
        //uncomment below and update the code to test postTemplateProgrammerTemplateDeploy
        //instance.postTemplateProgrammerTemplateDeploy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTemplateProgrammerTemplateVersion', function() {
      it('should call postTemplateProgrammerTemplateVersion successfully', function(done) {
        //uncomment below and update the code to test postTemplateProgrammerTemplateVersion
        //instance.postTemplateProgrammerTemplateVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTemplateProgrammerProject', function() {
      it('should call putTemplateProgrammerProject successfully', function(done) {
        //uncomment below and update the code to test putTemplateProgrammerProject
        //instance.putTemplateProgrammerProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTemplateProgrammerTemplate', function() {
      it('should call putTemplateProgrammerTemplate successfully', function(done) {
        //uncomment below and update the code to test putTemplateProgrammerTemplate
        //instance.putTemplateProgrammerTemplate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTemplateProgrammerTemplatePreview', function() {
      it('should call putTemplateProgrammerTemplatePreview successfully', function(done) {
        //uncomment below and update the code to test putTemplateProgrammerTemplatePreview
        //instance.putTemplateProgrammerTemplatePreview(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('templateProgrammerTemplateByTemplateId', function() {
      it('should call templateProgrammerTemplateByTemplateId successfully', function(done) {
        //uncomment below and update the code to test templateProgrammerTemplateByTemplateId
        //instance.templateProgrammerTemplateByTemplateId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
