/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.FunctionalCapabilityListResultResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FunctionalCapabilityListResultResponse', function() {
    it('should create an instance of FunctionalCapabilityListResultResponse', function() {
      // uncomment below and update the code to test FunctionalCapabilityListResultResponse
      //var instane = new Swagger.FunctionalCapabilityListResultResponse();
      //expect(instance).to.be.a(Swagger.FunctionalCapabilityListResultResponse);
    });

    it('should have the property attributeInfo (base name: "attributeInfo")', function() {
      // uncomment below and update the code to test the property attributeInfo
      //var instane = new Swagger.FunctionalCapabilityListResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new Swagger.FunctionalCapabilityListResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property functionalCapability (base name: "functionalCapability")', function() {
      // uncomment below and update the code to test the property functionalCapability
      //var instane = new Swagger.FunctionalCapabilityListResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Swagger.FunctionalCapabilityListResultResponse();
      //expect(instance).to.be();
    });

  });

}));
