/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.ModuleResultResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModuleResultResponse', function() {
    it('should create an instance of ModuleResultResponse', function() {
      // uncomment below and update the code to test ModuleResultResponse
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be.a(Swagger.ModuleResultResponse);
    });

    it('should have the property assemblyNumber (base name: "assemblyNumber")', function() {
      // uncomment below and update the code to test the property assemblyNumber
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property assemblyRevision (base name: "assemblyRevision")', function() {
      // uncomment below and update the code to test the property assemblyRevision
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property attributeInfo (base name: "attributeInfo")', function() {
      // uncomment below and update the code to test the property attributeInfo
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property containmentEntity (base name: "containmentEntity")', function() {
      // uncomment below and update the code to test the property containmentEntity
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property entityPhysicalIndex (base name: "entityPhysicalIndex")', function() {
      // uncomment below and update the code to test the property entityPhysicalIndex
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property isFieldReplaceable (base name: "isFieldReplaceable")', function() {
      // uncomment below and update the code to test the property isFieldReplaceable
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property isReportingAlarmsAllowed (base name: "isReportingAlarmsAllowed")', function() {
      // uncomment below and update the code to test the property isReportingAlarmsAllowed
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property manufacturer (base name: "manufacturer")', function() {
      // uncomment below and update the code to test the property manufacturer
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property moduleIndex (base name: "moduleIndex")', function() {
      // uncomment below and update the code to test the property moduleIndex
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property operationalStateCode (base name: "operationalStateCode")', function() {
      // uncomment below and update the code to test the property operationalStateCode
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property partNumber (base name: "partNumber")', function() {
      // uncomment below and update the code to test the property partNumber
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property serialNumber (base name: "serialNumber")', function() {
      // uncomment below and update the code to test the property serialNumber
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property vendorEquipmentType (base name: "vendorEquipmentType")', function() {
      // uncomment below and update the code to test the property vendorEquipmentType
      //var instane = new Swagger.ModuleResultResponse();
      //expect(instance).to.be();
    });

  });

}));
