/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PathResponseResultResponseEgressPhysicalInterface', function() {
    it('should create an instance of PathResponseResultResponseEgressPhysicalInterface', function() {
      // uncomment below and update the code to test PathResponseResultResponseEgressPhysicalInterface
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be.a(Swagger.PathResponseResultResponseEgressPhysicalInterface);
    });

    it('should have the property aclAnalysis (base name: "aclAnalysis")', function() {
      // uncomment below and update the code to test the property aclAnalysis
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property interfaceStatistics (base name: "interfaceStatistics")', function() {
      // uncomment below and update the code to test the property interfaceStatistics
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property interfaceStatsCollection (base name: "interfaceStatsCollection")', function() {
      // uncomment below and update the code to test the property interfaceStatsCollection
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property interfaceStatsCollectionFailureReason (base name: "interfaceStatsCollectionFailureReason")', function() {
      // uncomment below and update the code to test the property interfaceStatsCollectionFailureReason
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property pathOverlayInfo (base name: "pathOverlayInfo")', function() {
      // uncomment below and update the code to test the property pathOverlayInfo
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property qosStatistics (base name: "qosStatistics")', function() {
      // uncomment below and update the code to test the property qosStatistics
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property qosStatsCollection (base name: "qosStatsCollection")', function() {
      // uncomment below and update the code to test the property qosStatsCollection
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property qosStatsCollectionFailureReason (base name: "qosStatsCollectionFailureReason")', function() {
      // uncomment below and update the code to test the property qosStatsCollectionFailureReason
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property usedVlan (base name: "usedVlan")', function() {
      // uncomment below and update the code to test the property usedVlan
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

    it('should have the property vrfName (base name: "vrfName")', function() {
      // uncomment below and update the code to test the property vrfName
      //var instane = new Swagger.PathResponseResultResponseEgressPhysicalInterface();
      //expect(instance).to.be();
    });

  });

}));
