/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.SiteResultResponseSites();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SiteResultResponseSites', function() {
    it('should create an instance of SiteResultResponseSites', function() {
      // uncomment below and update the code to test SiteResultResponseSites
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be.a(Swagger.SiteResultResponseSites);
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property groupNameHierarchy (base name: "groupNameHierarchy")', function() {
      // uncomment below and update the code to test the property groupNameHierarchy
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property locationAddress (base name: "locationAddress")', function() {
      // uncomment below and update the code to test the property locationAddress
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property locationCountry (base name: "locationCountry")', function() {
      // uncomment below and update the code to test the property locationCountry
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property locationType (base name: "locationType")', function() {
      // uncomment below and update the code to test the property locationType
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parentId")', function() {
      // uncomment below and update the code to test the property parentId
      //var instane = new Swagger.SiteResultResponseSites();
      //expect(instance).to.be();
    });

  });

}));
