/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.TemplateDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemplateDTO', function() {
    it('should create an instance of TemplateDTO', function() {
      // uncomment below and update the code to test TemplateDTO
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be.a(Swagger.TemplateDTO);
    });

    it('should have the property author (base name: "author")', function() {
      // uncomment below and update the code to test the property author
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property deviceTypes (base name: "deviceTypes")', function() {
      // uncomment below and update the code to test the property deviceTypes
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdateTime (base name: "lastUpdateTime")', function() {
      // uncomment below and update the code to test the property lastUpdateTime
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property parentTemplateId (base name: "parentTemplateId")', function() {
      // uncomment below and update the code to test the property parentTemplateId
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "projectId")', function() {
      // uncomment below and update the code to test the property projectId
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property projectName (base name: "projectName")', function() {
      // uncomment below and update the code to test the property projectName
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property rollbackTemplateContent (base name: "rollbackTemplateContent")', function() {
      // uncomment below and update the code to test the property rollbackTemplateContent
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property rollbackTemplateParams (base name: "rollbackTemplateParams")', function() {
      // uncomment below and update the code to test the property rollbackTemplateParams
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property softwareType (base name: "softwareType")', function() {
      // uncomment below and update the code to test the property softwareType
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property softwareVariant (base name: "softwareVariant")', function() {
      // uncomment below and update the code to test the property softwareVariant
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property softwareVersion (base name: "softwareVersion")', function() {
      // uncomment below and update the code to test the property softwareVersion
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property templateContent (base name: "templateContent")', function() {
      // uncomment below and update the code to test the property templateContent
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property templateParams (base name: "templateParams")', function() {
      // uncomment below and update the code to test the property templateParams
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new Swagger.TemplateDTO();
      //expect(instance).to.be();
    });

  });

}));
