/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Swagger);
  }
}(this, function(expect, Swagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Swagger.WirelessInfoResultResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WirelessInfoResultResponse', function() {
    it('should create an instance of WirelessInfoResultResponse', function() {
      // uncomment below and update the code to test WirelessInfoResultResponse
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be.a(Swagger.WirelessInfoResultResponse);
    });

    it('should have the property adminEnabledPorts (base name: "adminEnabledPorts")', function() {
      // uncomment below and update the code to test the property adminEnabledPorts
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property apGroupName (base name: "apGroupName")', function() {
      // uncomment below and update the code to test the property apGroupName
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property deviceId (base name: "deviceId")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property ethMacAddress (base name: "ethMacAddress")', function() {
      // uncomment below and update the code to test the property ethMacAddress
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property flexGroupName (base name: "flexGroupName")', function() {
      // uncomment below and update the code to test the property flexGroupName
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property instanceTenantId (base name: "instanceTenantId")', function() {
      // uncomment below and update the code to test the property instanceTenantId
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property instanceUuid (base name: "instanceUuid")', function() {
      // uncomment below and update the code to test the property instanceUuid
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property lagModeEnabled (base name: "lagModeEnabled")', function() {
      // uncomment below and update the code to test the property lagModeEnabled
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property netconfEnabled (base name: "netconfEnabled")', function() {
      // uncomment below and update the code to test the property netconfEnabled
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property wirelessLicenseInfo (base name: "wirelessLicenseInfo")', function() {
      // uncomment below and update the code to test the property wirelessLicenseInfo
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

    it('should have the property wirelessPackageInstalled (base name: "wirelessPackageInstalled")', function() {
      // uncomment below and update the code to test the property wirelessPackageInstalled
      //var instane = new Swagger.WirelessInfoResultResponse();
      //expect(instance).to.be();
    });

  });

}));
